// @ts-nocheck
// tauri-specta currently emits unused event/channel globals for this app shape.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getHymn(id: number) : Promise<Result<Hymn, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_hymn", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchHymns(query: string) : Promise<Result<Hymn[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_hymns", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchAllHymns(query: string) : Promise<Result<Hymn[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_all_hymns", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchAllMusic(query: string) : Promise<Result<Hymn[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_all_music", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAlbums() : Promise<Result<Album[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_albums") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHymnsByAlbum(album: string) : Promise<Result<Hymn[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_hymns_by_album", { album }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createHymn(input: HymnWriteInput) : Promise<Result<Hymn, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_hymn", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateHymn(id: number, input: HymnWriteInput) : Promise<Result<Hymn, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_hymn", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHymn(id: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_hymn", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHymnAudioPath(hymnId: number) : Promise<Result<string | null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_hymn_audio_path", { hymnId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCollections(query: string | null) : Promise<Result<Collection[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_collections", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchCollections(query: string) : Promise<Result<CollectionSearchResult[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_collections", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchCollectionsContent(query: string) : Promise<Result<CollectionSearchResult[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_collections_content", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCollection(id: number) : Promise<Result<CollectionWithSongs, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_collection", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCollection(name: string, description: string | null, year: number | null, coverPath: string | null) : Promise<Result<Collection, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_collection", { name, description, year, coverPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCollection(id: number, name: string, description: string | null, year: number | null, coverPath: string | null) : Promise<Result<Collection, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_collection", { id, name, description, year, coverPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCollection(id: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_collection", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importCollectionSong(collectionId: number, path: string) : Promise<Result<CollectionSong, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_collection_song", { collectionId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkCollectionSongSync(songId: number) : Promise<Result<CollectionSongSyncStatus, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_collection_song_sync", { songId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resyncCollectionSong(songId: number) : Promise<Result<CollectionSong, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resync_collection_song", { songId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeCollectionSong(songId: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_collection_song", { songId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reorderCollectionSongs(collectionId: number, songIds: number[]) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reorder_collection_songs", { collectionId, songIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCollectionHymns(collectionId: number) : Promise<Result<Hymn[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_collection_hymns", { collectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addHymnToCollection(collectionId: number, hymnId: number, itemOrder: number) : Promise<Result<boolean, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_hymn_to_collection", { collectionId, hymnId, itemOrder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeHymnFromCollection(collectionId: number, hymnId: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_hymn_from_collection", { collectionId, hymnId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBibleVersions() : Promise<Result<BibleVersion[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_bible_versions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBooks(versionId: number) : Promise<Result<Book[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_books", { versionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getVerses(versionId: number, book: string, chapter: number) : Promise<Result<Verse[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_verses", { versionId, book, chapter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getVerseRange(versionId: number, book: string, chapter: number, start: number, end: number) : Promise<Result<Verse[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_verse_range", { versionId, book, chapter, start, end }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchBible(query: string, versionId: number | null) : Promise<Result<BibleSearchResult[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_bible", { query, versionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchBibleGlobal(query: string) : Promise<Result<BibleSearchResult[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_bible_global", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async projectBibleVerse(versionId: number, book: string, chapter: number, start: number, end: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("project_bible_verse", { versionId, book, chapter, start, end }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importBibleVersion(name: string, abbreviation: string, language: string, versesJson: string) : Promise<Result<number, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_bible_version", { name, abbreviation, language, versesJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Navigate bible projection by one verse forward or backward.
 * Handles chapter and book boundaries:
 * - Right arrow: next verse; if last verse in chapter, go to next chapter; if last chapter, go to next book.
 * - Left arrow: previous verse; if first verse in chapter, go to previous chapter's last verse; if first chapter, go to previous book's last chapter.
 */
async navigateBibleVerse(direction: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("navigate_bible_verse", { direction }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleFavorite(itemType: string, itemId: number) : Promise<Result<boolean, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_favorite", { itemType, itemId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFavorites(itemType: string) : Promise<Result<Favorite[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_favorites", { itemType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFavoriteHymns(query: string | null) : Promise<Result<Hymn[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_favorite_hymns", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFavoriteCollections(query: string | null) : Promise<Result<Collection[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_favorite_collections", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isFavorite(itemType: string, itemId: number) : Promise<Result<boolean, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_favorite", { itemType, itemId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllFavoriteIds(itemType: string) : Promise<Result<number[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_favorite_ids", { itemType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPresentations() : Promise<Result<Presentation[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_presentations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPresentation(id: number) : Promise<Result<Presentation, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_presentation", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createPresentation(title: string, aspectRatio: string) : Promise<Result<Presentation, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_presentation", { title, aspectRatio }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePresentation(id: number, title: string, aspectRatio: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_presentation", { id, title, aspectRatio }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePresentation(id: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_presentation", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSlides(presentationId: number) : Promise<Result<Slide[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_slides", { presentationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSlide(presentationId: number, contentJson: string, sortOrder: number) : Promise<Result<Slide, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_slide", { presentationId, contentJson, sortOrder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSlide(id: number, contentJson: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_slide", { id, contentJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSlide(id: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_slide", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reorderSlides(presentationId: number, slideIds: number[]) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reorder_slides", { presentationId, slideIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importSlja(path: string) : Promise<Result<Presentation, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_slja", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportSlja(presentationId: number, path: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_slja", { presentationId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getServices() : Promise<Result<Liturgy[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_services") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getService(id: number) : Promise<Result<LiturgyWithItems, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_service", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createService(title: string, date: string | null, notes: string | null) : Promise<Result<Liturgy, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_service", { title, date, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateService(id: number, title: string, date: string | null, notes: string | null) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_service", { id, title, date, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteService(id: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_service", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addServiceItem(serviceId: number, itemType: string, title: string, itemId: number | null, notes: string | null, parentId: number | null) : Promise<Result<LiturgyItem, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_service_item", { serviceId, itemType, title, itemId, notes, parentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeServiceItem(id: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_service_item", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reorderServiceItems(serviceId: number, itemIds: number[]) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reorder_service_items", { serviceId, itemIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async duplicateService(id: number) : Promise<Result<Liturgy, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("duplicate_service", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateServiceItem(id: number, title: string, notes: string | null) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_service_item", { id, title, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setServiceWeekDay(id: number, weekDay: number | null) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_service_week_day", { id, weekDay }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveServiceItemToParent(id: number, parentId: number | null) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_service_item_to_parent", { id, parentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCategoriesByTitle(title: string, keepItems: boolean) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_categories_by_title", { title, keepItems }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async countCategoryUsages(title: string) : Promise<Result<number, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_category_usages", { title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMediaLibraryCategories(language: string) : Promise<Result<MediaLibraryCategory[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_media_library_categories", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertMediaLibraryCategory(input: MediaLibraryCategoryInput) : Promise<Result<number, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_media_library_category", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteMediaLibraryCategory(id: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_media_library_category", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMediaLibraryItems(categoryId: number) : Promise<Result<MediaLibraryItem[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_media_library_items", { categoryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMediaLibraryItemsByDate(categoryId: number, date: string | null) : Promise<Result<MediaLibraryItem[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_media_library_items_by_date", { categoryId, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMediaLibraryItemDates(categoryId: number) : Promise<Result<string[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_media_library_item_dates", { categoryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertMediaLibraryItem(input: MediaLibraryItemInput) : Promise<Result<number, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_media_library_item", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteMediaLibraryItem(id: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_media_library_item", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchMediaLibraryItems(query: string) : Promise<Result<MediaLibraryItem[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_media_library_items", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getScheduledMediaItem(categoryId: number, date: string) : Promise<Result<MediaLibraryItem | null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_scheduled_media_item", { categoryId, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listScheduleDepartments() : Promise<Result<ScheduleDepartment[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_schedule_departments") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveScheduleDepartment(input: ScheduleDepartmentInput) : Promise<Result<ScheduleDepartment, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_schedule_department", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteScheduleDepartment(id: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_schedule_department", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reorderScheduleDepartments(departmentIds: number[]) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reorder_schedule_departments", { departmentIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async replaceScheduleDepartmentMembers(departmentId: number, members: string[]) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("replace_schedule_department_members", { departmentId, members }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getScheduleMonth(year: number, month: number) : Promise<Result<ScheduleMonthDetail, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_schedule_month", { year, month }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveScheduleMonthDays(year: number, month: number, days: ScheduleDayInput[]) : Promise<Result<ScheduleMonthDetail, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_schedule_month_days", { year, month, days }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateScheduleMonth(input: ScheduleGenerationRequest) : Promise<Result<ScheduleMonthDetail, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_schedule_month", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setScheduleDayResponsibleDepartment(scheduleDayId: number, responsibleDepartmentId: number | null) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_schedule_day_responsible_department", { scheduleDayId, responsibleDepartmentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveScheduleDayAssignments(input: ScheduleAssignmentInput) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_schedule_day_assignments", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateScheduleDayDepartmentPeoplePerDay(scheduleDayDepartmentId: number, peoplePerDay: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_schedule_day_department_people_per_day", { scheduleDayDepartmentId, peoplePerDay }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetScheduleDayDepartmentManualOverride(scheduleDayDepartmentId: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_schedule_day_department_manual_override", { scheduleDayDepartmentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async audioPlay(filePath: string, positionMs: number | null, preserveLivePosition: boolean | null) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("audio_play", { filePath, positionMs, preserveLivePosition }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async audioPlayVariants(sungFilePath: string, karaokeFilePath: string, activeMode: string, positionMs: number | null) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("audio_play_variants", { sungFilePath, karaokeFilePath, activeMode, positionMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async audioPlayAlert(filePath: string | null, volume: number | null) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("audio_play_alert", { filePath, volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async audioPause() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("audio_pause") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async audioResume() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("audio_resume") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async audioSetOutputMuted(muted: boolean) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("audio_set_output_muted", { muted }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async audioSwitchVariant(activeMode: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("audio_switch_variant", { activeMode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async audioStop() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("audio_stop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async audioSeek(positionMs: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("audio_seek", { positionMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async audioSetVolume(volume: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("audio_set_volume", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async audioGetPosition() : Promise<Result<number, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("audio_get_position") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async audioGetStatus() : Promise<Result<AudioStatusPayload, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("audio_get_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSyncPoints(hymnId: number) : Promise<Result<SyncPoint[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sync_points", { hymnId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSyncPoints(hymnId: number, points: SyncPoint[]) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_sync_points", { hymnId, points }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableMonitors() : Promise<Result<MonitorInfo[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_monitors") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openProjectorWindow(monitorId: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_projector_window", { monitorId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeProjectorWindow() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_projector_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openReturnWindow(monitorId: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_return_window", { monitorId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeReturnWindow() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_return_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCurrentSlide(slideData: SlideContent) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_current_slide", { slideData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSlideOnProjector(slideData: SlideContent) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_slide_on_projector", { slideData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSlideOnReturn(slideData: SlideContent) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_slide_on_return", { slideData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentSlide() : Promise<Result<SlideContent | null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_slide") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearCurrentSlide() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_current_slide") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSlideContext(contextData: SlideContext) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_slide_context", { contextData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSlideContext() : Promise<Result<SlideContext | null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_slide_context") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleBlackScreen() : Promise<Result<OverlayState, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_black_screen") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleLogoScreen() : Promise<Result<OverlayState, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_logo_screen") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOverlayState() : Promise<Result<OverlayState, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_overlay_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAlert(text: string, isTicker: boolean) : Promise<Result<OverlayState, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_alert", { text, isTicker }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearAlert() : Promise<Result<OverlayState, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_alert") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async identifyMonitors() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identify_monitors") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMonitorConfig(monitorId: string, role: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_monitor_config", { monitorId, role }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMonitorConfigs() : Promise<Result<MonitorConfig[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_monitor_configs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startStreamingServer(port: number | null) : Promise<Result<StreamingInfo, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_streaming_server", { port }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopStreamingServer() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_streaming_server") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStreamingStatus() : Promise<Result<StreamingInfo, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_streaming_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setStreamingBroadcast(enabled: boolean) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_streaming_broadcast", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Forward a video state snapshot or control command from the master player
 * (running in the main Tauri window) to the SSE video broadcaster, so
 * streaming clients (OBS, external browsers) can stay synchronized.
 * 
 * Call this command whenever the video state changes (play, pause, seek,
 * time update). The frontend should throttle time-update calls to avoid
 * flooding the SSE channel (e.g. max once per 500 ms).
 */
async broadcastVideoStateToStreaming(payload: VideoStreamPayload) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("broadcast_video_state_to_streaming", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSetting(key: string) : Promise<Result<Setting, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSetting(key: string, value: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllSettings() : Promise<Result<Setting[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearDatabase() : Promise<Result<ClearDatabaseResult, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_database") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateGlobalShortcut(action: string, shortcutStr: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_global_shortcut", { action, shortcutStr }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startTimer(mode: string, durationMs: number | null) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_timer", { mode, durationMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseTimer() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeTimer() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetTimer() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async adjustCountdownTimer(deltaMs: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("adjust_countdown_timer", { deltaMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTimerState() : Promise<Result<TimerStateData, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_timer_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addLap() : Promise<Result<number, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_lap") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startCountdownProjection(contextTitle: string, countdownTitle: string, initialTimeMs: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_countdown_projection", { contextTitle, countdownTitle, initialTimeMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startStopwatchProjection(contextTitle: string, stopwatchTitle: string, initialTimeMs: number) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_stopwatch_projection", { contextTitle, stopwatchTitle, initialTimeMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopUtilityProjection() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_utility_projection") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startClockProjection(contextTitle: string, clockTitle: string, use24Hour: boolean, showDate: boolean) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_clock_projection", { contextTitle, clockTitle, use24Hour, showDate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startMigration(oldDbPath: string, options: MigrationOptions) : Promise<Result<MigrationRunInfo, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_migration", { oldDbPath, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMigrationProgress(runId: string) : Promise<Result<MigrationProgress, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_migration_progress", { runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelMigration(runId: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_migration", { runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMigrationReport(runId: string) : Promise<Result<MigrationReport, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_migration_report", { runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkForUpdates() : Promise<Result<UpdateInfo | null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_updates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installUpdate() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Broadcasts projection display settings (font size + family) to all windows.
 * Must route through Rust because JS `emit()` is scoped to the current window;
 * `app.emit()` from Rust is global and reaches the projector/return webviews.
 */
async broadcastProjectionDisplay(fontSize: number, fontFamily: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("broadcast_projection_display", { fontSize, fontFamily }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runLottery(names: string[]) : Promise<Result<string, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_lottery", { names }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async formatText(text: string, format: string) : Promise<Result<string, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("format_text", { text, format }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async copyImageToMedia(imagePath: string) : Promise<Result<string, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_image_to_media", { imagePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async copyVideoToMedia(videoPath: string) : Promise<Result<string, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_video_to_media", { videoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get metadata for a video file.
 * 
 * Accepts any absolute OS path (e.g. user-picked via file dialog) or a managed
 * relative path (`media/videos/...`) resolved against `app_data_dir`.
 * SafePath is intentionally NOT used here — this command is for user-picked files
 * that live anywhere on disk, not for managed internal paths.
 * 
 * The native parser runs synchronously (fast). If it fails and ffprobe is
 * enabled, the ffprobe fallback can block up to 4 seconds — that work is
 * offloaded to `tokio::task::spawn_blocking` so the IPC bridge stays
 * responsive on Windows during the wait.
 */
async getVideoMetadata(path: string) : Promise<Result<VideoMetadata, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_video_metadata", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openMediaFolder() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_media_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async spotlightOpen() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spotlight_open") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Called from the spotlight window when the user selects a result.
 * - kind = "navigate": focuses main window, emits spotlight-navigated event with route
 * - kind = "action": emits spotlight-action to main window for execution
 * - kind = "hide": just hides the spotlight window
 */
async spotlightSelect(kind: string, payload: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spotlight_select", { kind, payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Hides the spotlight window. Called when the spotlight loses focus.
 */
async spotlightHide() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spotlight_hide") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async planPackSync(forceRefresh: boolean | null, previewLanguages: string[] | null) : Promise<Result<PackSyncPlan, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plan_pack_sync", { forceRefresh, previewLanguages }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startPackSync(items: PackSyncPlanItem[] | null, selectedLanguages: string[] | null) : Promise<Result<string, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_pack_sync", { items, selectedLanguages }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelPackSync(runId: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_pack_sync", { runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearManifestCache() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_manifest_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateYoutubeApiKey(key: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_youtube_api_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchYoutubeChannel(url: string, apiKey: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_youtube_channel", { url, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addYoutubePlaylist(input: AddPlaylistInput, apiKey: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_youtube_playlist", { input, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getYoutubePlaylists() : Promise<Result<OnlineVideoPlaylist[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_youtube_playlists") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getYoutubePlaylistVideos(playlistId: string) : Promise<Result<OnlineVideo[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_youtube_playlist_videos", { playlistId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshYoutubePlaylist(playlistId: string, apiKey: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_youtube_playlist", { playlistId, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteYoutubePlaylist(playlistId: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_youtube_playlist", { playlistId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteVideoLocalFile(videoId: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_video_local_file", { videoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ensureYtdlp() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_ytdlp") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateYtdlp() : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_ytdlp") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadOnlineVideo(videoId: string, playlistId: string, quality: string) : Promise<Result<string, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_online_video", { videoId, playlistId, quality }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(runId: string) : Promise<Result<null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchOnlinePlaylists(query: string) : Promise<Result<OnlinePlaylistSearchResult[], AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_online_playlists", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async findOnlineVideoByYtId(ytVideoId: string) : Promise<Result<OnlineVideo | null, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("find_online_video_by_yt_id", { ytVideoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startVideoServer() : Promise<Result<VideoServerInfo, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_video_server") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getVideoServerStatus() : Promise<Result<VideoServerInfo, AppErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_video_server_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Online Videos feature — input for adding a playlist via Tauri command.
 */
export type AddPlaylistInput = { playlistId: string; channelId: string; channelTitle: string; playlistTitle: string; thumbnailUrl: string }
export type Album = { name: string; hymnCount: number }
export type AlertState = { text: string; isVisible: boolean; isTicker: boolean }
export type AppErrorResponse = { code: string; message: string; details: string | null }
export type AudioStatusPayload = { positionMs: number; durationMs: number; isPlaying: boolean; isPaused: boolean; volume: number; currentFile: string | null }
export type BibleSearchResult = { verse: Verse; bookName: string; snippet: string; versionAbbreviation: string }
export type BibleVersion = { id: number; name: string; abbreviation: string; language: string; isBuiltin: boolean }
export type Book = { name: string; chapterCount: number }
export type ClearDatabaseResult = { success: boolean }
export type Collection = { id: number; name: string; description: string | null; year: number | null; coverPath: string | null; autoCoverPath: string | null; songCount: number; sourceType: string; apiAlbumId: number; createdAt: string; updatedAt: string }
export type CollectionSearchResult = { kind: string; collectionId: number; songId: number; collectionName: string; title: string; coverPath: string | null; snippet: string }
export type CollectionSong = { id: number; collectionId: number; sourcePath: string; sourceFormat: string; sourceHash: string | null; sourceMtimeMs: number; cachePresentationId: number; syncStatus: CollectionSongSyncStatus; lastSyncAt: string | null; itemOrder: number; createdAt: string; updatedAt: string; cachePresentationTitle: string | null }
export type CollectionSongSyncStatus = "inSync" | "stale" | "missingSource" | "error"
export type CollectionWithSongs = { collection: Collection; songs: CollectionSong[] }
export type Favorite = { id: number; itemType: string; itemId: number; createdAt: string }
export type Hymn = { id: number; number: number | null; title: string; author: string | null; album: string | null; lyrics: string | null; chords: string | null; audioPath: string | null; playbackPath: string | null; category: string | null; notes: string | null; coverPath: string | null; lyricsSync: string | null; apiMusicId: number; createdAt: string; updatedAt: string }
export type HymnWriteInput = { number: number | null; title: string; author: string | null; album: string | null; lyrics: string | null; chords: string | null; audioPath: string | null; playbackPath: string | null; category: string | null; notes: string | null; coverPath: string | null; lyricsSync: string | null }
export type Liturgy = { id: number; title: string; date: string | null; notes: string | null; createdAt: string; updatedAt: string; itemCount: number; hymnCount: number; weekDay: number | null }
export type LiturgyItem = { id: number; serviceId: number; itemType: string; itemId: number | null; title: string; itemOrder: number; notes: string | null; parentId: number | null }
export type LiturgyWithItems = { service: Liturgy; items: LiturgyItem[] }
export type MediaLibraryCategory = { id: number; name: string; sortOrder: number; idLanguage: string }
export type MediaLibraryCategoryInput = { id: number | null; name: string; sortOrder: number; idLanguage: string }
export type MediaLibraryItem = { id: number; categoryId: number; name: string; filePath: string; fileType: string; thumbnailPath: string | null; scheduledDate: string | null; sortOrder: number; createdAt: string }
export type MediaLibraryItemInput = { id: number | null; categoryId: number; name: string; filePath: string; fileType: string; thumbnailPath: string | null; scheduledDate: string | null; sortOrder: number }
export type MigrationDomainReport = { domain: string; imported: number; skipped: number }
export type MigrationErrorItem = { domain: string; code: string; message: string; context?: string | null }
export type MigrationOptions = { includeHymns?: boolean; includeBible?: boolean; includeFavorites?: boolean; includeServices?: boolean; includeSettings?: boolean; replaceExisting?: boolean }
export type MigrationProgress = { runId: string; step: string; completed: number; total: number; percent: number; etaSeconds: number; message: string; status: string; updatedAt: string }
export type MigrationReport = { runId: string; status: string; startedAt: string; finishedAt: string | null; sourcePath: string; domains: MigrationDomainReport[]; errors: MigrationErrorItem[] }
export type MigrationRunInfo = { runId: string; startedAt: string; sourcePath: string }
export type MonitorConfig = { id: number; monitorId: string; role: string; enabled: boolean }
export type MonitorInfo = { id: string; name: string; friendlyName: string | null; manufacturer: string | null; model: string | null; connectionType: string | null; width: number; height: number; isPrimary: boolean; x: number; y: number; scaleFactor: number }
/**
 * Online Videos feature — search result for command palette FTS5 search.
 */
export type OnlinePlaylistSearchResult = { dbId: number; playlistId: string; title: string; channelTitle: string; snippet: string; coverPath: string | null }
/**
 * Online Videos feature — individual video record (queries SELECT explicitly).
 */
export type OnlineVideo = { id: number; idPlaylist: number; videoId: string; sequence: number; title: string | null; description: string | null; images: string | null; status: string; error: string | null; localPath: string | null; durationSeconds: number | null }
/**
 * Online Videos feature — playlist view model (queries SELECT explicitly).
 * `channel_title` comes from JOIN on `online_videos_channels`.
 * `video_count` is a computed COUNT(*) subquery.
 */
export type OnlineVideoPlaylist = { id: number; idChannel: number | null; playlistId: string; title: string | null; description: string | null; images: string | null; status: string; error: string | null; coverPath: string | null; channelTitle: string | null; videoCount: number | null }
export type OverlayState = { blackScreen: boolean; logoScreen: boolean; alert: AlertState | null }
export type PackSyncFileItem = { path: string; hymnApiId: number | null; albumApiId: number | null; fileType: string; size: number; albumName: string | null }
export type PackSyncPlan = { manifestVersion: number; items: PackSyncPlanItem[]; totalDownloadSize: number; totalDownloadCount: number; availableLanguages: string[]; selectedLanguages: string[] }
export type PackSyncPlanItem = { packId: string; packUrl: string; packVersion: number; packSize: number; packSha256: string; localExtractedVersion: number; localDbVersion: number; needsDownload: boolean; needsDbUpdate: boolean; fileCount: number; files: PackSyncFileItem[]; language: string }
export type Presentation = { id: number; title: string; author: string | null; aspectRatio: string; libraryKind: string | null; filePath: string | null; createdAt: string; updatedAt: string }
export type ScheduleAssignment = { id: number; scheduleDayDepartmentId: number; memberId: number; sortOrder: number; createdAt: string; member: ScheduleDepartmentMember | null }
export type ScheduleAssignmentInput = { scheduleDayDepartmentId: number; memberIds: number[] }
export type ScheduleDay = { id: number; scheduleMonthId: number; serviceDate: string; label: string | null; sourceKind: string; responsibleDepartmentId: number | null; createdAt: string; updatedAt: string; responsibleDepartment: ScheduleDepartment | null; departments: ScheduleDayDepartment[] }
export type ScheduleDayDepartment = { id: number; scheduleDayId: number; departmentId: number; peoplePerDay: number; manualOverride: boolean; createdAt: string; updatedAt: string; department: ScheduleDepartment | null; assignments: ScheduleAssignment[] }
export type ScheduleDayInput = { serviceDate: string; label: string | null; sourceKind: string | null; responsibleDepartmentId: number | null; departmentIds: number[] }
export type ScheduleDepartment = { id: number; code: string | null; namePt: string | null; nameEn: string | null; nameEs: string | null; icon: string; color: string; peoplePerDay: number; shuffleOnGenerate: boolean; groupDatesInPrint: boolean; repeatMembersInGroupedDates: boolean; sortOrder: number; isSystem: boolean; isActive: boolean; createdAt: string; updatedAt: string; members: ScheduleDepartmentMember[] }
export type ScheduleDepartmentInput = { id: number | null; code: string | null; namePt: string | null; nameEn: string | null; nameEs: string | null; icon: string; color: string; peoplePerDay: number; shuffleOnGenerate: boolean; groupDatesInPrint: boolean; repeatMembersInGroupedDates: boolean; sortOrder: number; isActive: boolean }
export type ScheduleDepartmentMember = { id: number; departmentId: number; name: string; sortOrder: number; isActive: boolean; createdAt: string; updatedAt: string }
export type ScheduleGenerationRequest = { year: number; month: number; overwriteManual: boolean }
export type ScheduleMonth = { id: number; year: number; month: number; notes: string | null; createdAt: string; updatedAt: string }
export type ScheduleMonthDetail = { month: ScheduleMonth; departments: ScheduleDepartment[]; days: ScheduleDay[] }
export type Setting = { key: string; value: string }
export type Slide = { id: number; presentationId: number; slideIndex: number; slideType: string; content: string; notes: string | null; transition: string | null }
export type SlideContent = { slideType: string; text: string | null; title: string | null; subtitle: string | null; label: string | null; videoPath: string | null; backgroundImage: string | null; backgroundColor: string | null; audioPath: string | null; autoPlay: boolean | null; loop: boolean | null; muted: boolean | null; mode: string | null; textColor: string | null; textSize: number | null; videoUrl: string | null; videoId: string | null; videoSource: string | null; videoTitle: string | null }
export type SlideContext = { next: SlideContent | null; index: number; total: number; title: string; currentSlideStartMs: number | null; nextSlideStartMs: number | null; audioDurationMs: number | null }
export type StreamingInfo = { isRunning: boolean; ip: string | null; port: number; urls: StreamingUrls | null; connections: number; broadcastEnabled: boolean }
export type StreamingUrls = { music: string; bible: string; returnMonitor: string }
export type SyncPoint = { slideIndex: number; timestampMs: number; instrumentalTimestampMs?: number | null }
export type TimerMode = "countdown" | "stopwatch"
export type TimerStateData = { mode: TimerMode; isRunning: boolean; currentTimeMs: number; durationMs: number; laps: number[] }
export type UpdateInfo = { version: string; currentVersion: string; notes: string | null }
export type Verse = { id: number; versionId: number; book: string; chapter: number; verse: number; text: string }
export type VideoMetadata = { durationMs: number; width: number; height: number; fileSize: number; format: string }
export type VideoServerInfo = { isRunning: boolean; port: number; accessToken: string }
/**
 * Payload forwarded from the frontend video master to streaming SSE clients.
 * The `event_type` field distinguishes state snapshots from transient commands
 * so the broadcaster knows whether to replay the message to new connections.
 */
export type VideoStreamPayload = { 
/**
 * "state" = sticky snapshot (replayed on connect), "cmd" = transient command.
 */
eventType: string; 
/**
 * play | pause | seek | state
 */
action: string; 
/**
 * Current playback position in seconds (present for "state" and "seek").
 */
currentTime: number | null; 
/**
 * Total duration in seconds (present for "state").
 */
duration: number | null; 
/**
 * Whether the video is paused (present for "state").
 */
paused: boolean | null; 
/**
 * Volume 0..1 (present for "state").
 */
volume: number | null; 
/**
 * YouTube video ID (present when source == "youtube").
 */
videoId: string | null; 
/**
 * Video source: "youtube" | "local" | null.
 */
videoSource: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
