//! Typed Tauri events emitted by the Rust video pipeline
//! (see `docs/plans/2026-04-17-rust-video-pipeline.md`, Task 4.2).
//!
//! Wire format is locked down via `#[serde(rename_all = "camelCase")]` so the
//! frontend bindings (auto-generated by `tauri-specta`) can call
//! `VideoPipelineOffer.listen(handle, ...)` without `as any` casts.
//!
//! Events:
//! - [`VideoPipelineOffer`] — Rust → frontend; carries the SDP offer for a
//!   freshly-attached webrtcbin consumer.
//! - [`VideoPipelineIce`] — Rust → frontend; carries a local ICE candidate.
//! - [`VideoPipelineState`] — Rust → frontend; periodic snapshot of playback
//!   state (Task 2.3 will broadcast at 10Hz; Task 4.1 only wires the type).
//! - [`VideoPipelineEnded`] — Rust → frontend; emitted on EOS (Task 3.1 wires
//!   the bus listener; Task 4.1 only registers the type).
#![allow(dead_code)]

use serde::{Deserialize, Serialize};
use specta::Type;
use tauri_specta::Event;

/// Outbound: a webrtcbin produced an SDP offer for `window_label`.
#[derive(Debug, Clone, Serialize, Deserialize, Type, Event)]
#[serde(rename_all = "camelCase")]
pub struct VideoPipelineOffer {
    pub window_label: String,
    pub sdp: String,
}

/// Outbound: webrtcbin gathered a local ICE candidate for `window_label`.
#[derive(Debug, Clone, Serialize, Deserialize, Type, Event)]
#[serde(rename_all = "camelCase")]
pub struct VideoPipelineIce {
    pub window_label: String,
    pub candidate: String,
    pub sdp_m_line_index: u32,
}

/// Outbound: periodic playback snapshot (position/duration/paused/volume).
#[derive(Debug, Clone, Serialize, Deserialize, Type, Event)]
#[serde(rename_all = "camelCase")]
pub struct VideoPipelineState {
    pub position_secs: f64,
    pub duration_secs: f64,
    pub paused: bool,
    pub volume: f32,
}

/// Outbound: the active media reached EOS (end-of-stream).
#[derive(Debug, Clone, Serialize, Deserialize, Type, Event)]
#[serde(rename_all = "camelCase")]
pub struct VideoPipelineEnded {}
