//! Signaling primitives for the WebRTC video consumers
//! (see `docs/plans/2026-04-17-rust-video-pipeline.md`, Task 1.3).
//!
//! This module is intentionally **Tauri-agnostic**. It defines the typed
//! payloads that flow Rust ↔ frontend during the SDP/ICE handshake plus a
//! [`SignalingChannel`] abstraction that the consumer code uses to publish
//! Rust-side events without taking a hard dependency on `tauri::AppHandle`.
//!
//! Task 4.1 supplies the production [`SignalingChannel`] implementation that
//! bridges to `tauri::Emitter::emit`. Tests use [`NoopSignalingChannel`] (drops
//! everything) or [`MpscSignalingChannel`] (forwards into a
//! `std::sync::mpsc::Sender`) to assert behaviour without spinning up a Tauri
//! app handle.
//!
//! Field naming on the payload structs is locked down: Task 4.1 will register
//! Tauri events whose JSON wire format must match these structs exactly.
#![allow(dead_code)]

use std::sync::mpsc::Sender;

/// Payload for the Rust → frontend "WebRTC offer ready" event.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct OfferPayload {
    /// Tauri window label this offer targets (e.g. `"projector"`, `"return"`).
    pub window_label: String,
    /// SDP offer text generated by the Rust webrtcbin.
    pub sdp: String,
}

/// Payload for the frontend → Rust "WebRTC answer" command.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct AnswerPayload {
    /// Tauri window label whose consumer should accept this answer.
    pub window_label: String,
    /// SDP answer text produced by the frontend `RTCPeerConnection`.
    pub sdp: String,
}

/// Payload used in both directions for trickle ICE candidates.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct IcePayload {
    /// Tauri window label the candidate belongs to.
    pub window_label: String,
    /// ICE candidate string (`"candidate:..."`).
    pub candidate: String,
    /// SDP m-line index this candidate applies to.
    pub sdp_m_line_index: u32,
}

/// Outbound signaling sink (Rust → frontend).
///
/// Implementations may push payloads through Tauri events (production), drop
/// them (tests that only need to verify side-effect-free flows), or forward
/// them to an in-memory channel for assertions.
pub trait SignalingChannel: Send + Sync {
    /// Publish an SDP offer for a specific consumer/window.
    fn emit_offer(&self, payload: OfferPayload);
    /// Publish a local ICE candidate for a specific consumer/window.
    fn emit_ice(&self, payload: IcePayload);
}

/// `SignalingChannel` that silently drops every event.
///
/// Useful for tests that exercise the consumer state machine without caring
/// about the outbound traffic.
#[derive(Debug, Default)]
pub struct NoopSignalingChannel;

impl SignalingChannel for NoopSignalingChannel {
    fn emit_offer(&self, _payload: OfferPayload) {}
    fn emit_ice(&self, _payload: IcePayload) {}
}

/// Event delivered through [`MpscSignalingChannel`].
#[derive(Debug, Clone)]
pub enum SignalingEvent {
    Offer(OfferPayload),
    Ice(IcePayload),
}

/// `SignalingChannel` that forwards every payload into a `mpsc::Sender`.
///
/// Receivers are owned by the test and pulled with `recv_timeout`.
pub struct MpscSignalingChannel {
    tx: Sender<SignalingEvent>,
}

impl MpscSignalingChannel {
    /// Build a channel that forwards events into `tx`.
    pub fn new(tx: Sender<SignalingEvent>) -> Self {
        Self { tx }
    }
}

impl SignalingChannel for MpscSignalingChannel {
    fn emit_offer(&self, payload: OfferPayload) {
        // Receiver may be dropped before the channel; nothing actionable here.
        let _ = self.tx.send(SignalingEvent::Offer(payload));
    }

    fn emit_ice(&self, payload: IcePayload) {
        let _ = self.tx.send(SignalingEvent::Ice(payload));
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::mpsc::channel;
    use std::time::Duration;

    #[test]
    fn noop_channel_drops_events() {
        let chan = NoopSignalingChannel;
        chan.emit_offer(OfferPayload {
            window_label: "projector".into(),
            sdp: "v=0".into(),
        });
        chan.emit_ice(IcePayload {
            window_label: "projector".into(),
            candidate: "candidate:1".into(),
            sdp_m_line_index: 0,
        });
        // Just asserting it compiled and didn't panic.
    }

    #[test]
    fn mpsc_channel_forwards_offer_and_ice() {
        let (tx, rx) = channel();
        let chan = MpscSignalingChannel::new(tx);

        chan.emit_offer(OfferPayload {
            window_label: "projector".into(),
            sdp: "v=0\r\n".into(),
        });
        chan.emit_ice(IcePayload {
            window_label: "projector".into(),
            candidate: "candidate:1 1 UDP 2122252543 192.168.1.1 9 typ host".into(),
            sdp_m_line_index: 0,
        });

        match rx.recv_timeout(Duration::from_millis(100)) {
            Ok(SignalingEvent::Offer(p)) => {
                assert_eq!(p.window_label, "projector");
                assert_eq!(p.sdp, "v=0\r\n");
            }
            other => panic!("expected Offer, got {other:?}"),
        }
        match rx.recv_timeout(Duration::from_millis(100)) {
            Ok(SignalingEvent::Ice(p)) => {
                assert_eq!(p.window_label, "projector");
                assert_eq!(p.sdp_m_line_index, 0);
                assert!(p.candidate.starts_with("candidate:1"));
            }
            other => panic!("expected Ice, got {other:?}"),
        }
    }

    #[test]
    fn payloads_round_trip_json() {
        let offer = OfferPayload {
            window_label: "main".into(),
            sdp: "v=0\r\n".into(),
        };
        let json = serde_json::to_string(&offer).expect("serialize offer");
        // camelCase rename_all means windowLabel, not window_label.
        assert!(json.contains("\"windowLabel\":\"main\""));
        let parsed: OfferPayload = serde_json::from_str(&json).expect("deserialize offer");
        assert_eq!(parsed.window_label, "main");

        let ice = IcePayload {
            window_label: "return".into(),
            candidate: "candidate:42".into(),
            sdp_m_line_index: 7,
        };
        let json = serde_json::to_string(&ice).expect("serialize ice");
        assert!(json.contains("\"sdpMLineIndex\":7"));
        let parsed: IcePayload = serde_json::from_str(&json).expect("deserialize ice");
        assert_eq!(parsed.sdp_m_line_index, 7);

        let answer = AnswerPayload {
            window_label: "main".into(),
            sdp: "v=0\r\n".into(),
        };
        let json = serde_json::to_string(&answer).expect("serialize answer");
        assert!(json.contains("\"windowLabel\":\"main\""));
    }
}
