import { describe, it, expect } from "vitest";
import { signEnvelope } from "../crypto";

describe("signEnvelope", () => {
  it("matches Rust reference vector", async () => {
    // Reference vector generated by:
    //   Rust: sign(b"secret", 42, "n1", "slide.next", "{}") → BASE64_STANDARD_NO_PAD
    // Run `cargo test remote::hmac_util::tests::print_reference_vector -- --nocapture` to regenerate.
    const EXPECTED = "dyX7H/vwxDPiU97xiva7S5KmMc4hhNyDzzeiV0dmqjw";

    const keyBytes = new TextEncoder().encode("secret");
    const sig = await signEnvelope(keyBytes, 42, "n1", "slide.next", "{}");

    expect(sig).toBe(EXPECTED);
  });

  it("produces different signatures for different ops", async () => {
    const keyBytes = new TextEncoder().encode("secret");
    const sig1 = await signEnvelope(keyBytes, 42, "n1", "slide.next", "{}");
    const sig2 = await signEnvelope(keyBytes, 42, "n1", "slide.prev", "{}");
    expect(sig1).not.toBe(sig2);
  });

  it("produces different signatures for different keys", async () => {
    const sig1 = await signEnvelope(new TextEncoder().encode("key1"), 42, "n1", "slide.next", "{}");
    const sig2 = await signEnvelope(new TextEncoder().encode("key2"), 42, "n1", "slide.next", "{}");
    expect(sig1).not.toBe(sig2);
  });

  it("produces different signatures for different timestamps", async () => {
    const keyBytes = new TextEncoder().encode("secret");
    const sig1 = await signEnvelope(keyBytes, 42, "n1", "slide.next", "{}");
    const sig2 = await signEnvelope(keyBytes, 43, "n1", "slide.next", "{}");
    expect(sig1).not.toBe(sig2);
  });
});
