/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilitiesRouteImport } from './routes/utilities'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReturnRouteImport } from './routes/return'
import { Route as ProjectorRouteImport } from './routes/projector'
import { Route as PresentationsRouteRouteImport } from './routes/presentations/route'
import { Route as HymnalRouteRouteImport } from './routes/hymnal/route'
import { Route as BibleRouteRouteImport } from './routes/bible/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PresentationsIndexRouteImport } from './routes/presentations/index'
import { Route as HymnalIndexRouteImport } from './routes/hymnal/index'
import { Route as BibleIndexRouteImport } from './routes/bible/index'
import { Route as PresentationsPresentationIdRouteImport } from './routes/presentations/$presentationId'
import { Route as HymnalHymnIdRouteImport } from './routes/hymnal/$hymnId'

const UtilitiesRoute = UtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnRoute = ReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectorRoute = ProjectorRouteImport.update({
  id: '/projector',
  path: '/projector',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsRouteRoute = PresentationsRouteRouteImport.update({
  id: '/presentations',
  path: '/presentations',
  getParentRoute: () => rootRouteImport,
} as any)
const HymnalRouteRoute = HymnalRouteRouteImport.update({
  id: '/hymnal',
  path: '/hymnal',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleRouteRoute = BibleRouteRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsIndexRoute = PresentationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PresentationsRouteRoute,
} as any)
const HymnalIndexRoute = HymnalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HymnalRouteRoute,
} as any)
const BibleIndexRoute = BibleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibleRouteRoute,
} as any)
const PresentationsPresentationIdRoute =
  PresentationsPresentationIdRouteImport.update({
    id: '/$presentationId',
    path: '/$presentationId',
    getParentRoute: () => PresentationsRouteRoute,
  } as any)
const HymnalHymnIdRoute = HymnalHymnIdRouteImport.update({
  id: '/$hymnId',
  path: '/$hymnId',
  getParentRoute: () => HymnalRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bible': typeof BibleRouteRouteWithChildren
  '/hymnal': typeof HymnalRouteRouteWithChildren
  '/presentations': typeof PresentationsRouteRouteWithChildren
  '/projector': typeof ProjectorRoute
  '/return': typeof ReturnRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/utilities': typeof UtilitiesRoute
  '/hymnal/$hymnId': typeof HymnalHymnIdRoute
  '/presentations/$presentationId': typeof PresentationsPresentationIdRoute
  '/bible/': typeof BibleIndexRoute
  '/hymnal/': typeof HymnalIndexRoute
  '/presentations/': typeof PresentationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projector': typeof ProjectorRoute
  '/return': typeof ReturnRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/utilities': typeof UtilitiesRoute
  '/hymnal/$hymnId': typeof HymnalHymnIdRoute
  '/presentations/$presentationId': typeof PresentationsPresentationIdRoute
  '/bible': typeof BibleIndexRoute
  '/hymnal': typeof HymnalIndexRoute
  '/presentations': typeof PresentationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bible': typeof BibleRouteRouteWithChildren
  '/hymnal': typeof HymnalRouteRouteWithChildren
  '/presentations': typeof PresentationsRouteRouteWithChildren
  '/projector': typeof ProjectorRoute
  '/return': typeof ReturnRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/utilities': typeof UtilitiesRoute
  '/hymnal/$hymnId': typeof HymnalHymnIdRoute
  '/presentations/$presentationId': typeof PresentationsPresentationIdRoute
  '/bible/': typeof BibleIndexRoute
  '/hymnal/': typeof HymnalIndexRoute
  '/presentations/': typeof PresentationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bible'
    | '/hymnal'
    | '/presentations'
    | '/projector'
    | '/return'
    | '/services'
    | '/settings'
    | '/utilities'
    | '/hymnal/$hymnId'
    | '/presentations/$presentationId'
    | '/bible/'
    | '/hymnal/'
    | '/presentations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projector'
    | '/return'
    | '/services'
    | '/settings'
    | '/utilities'
    | '/hymnal/$hymnId'
    | '/presentations/$presentationId'
    | '/bible'
    | '/hymnal'
    | '/presentations'
  id:
    | '__root__'
    | '/'
    | '/bible'
    | '/hymnal'
    | '/presentations'
    | '/projector'
    | '/return'
    | '/services'
    | '/settings'
    | '/utilities'
    | '/hymnal/$hymnId'
    | '/presentations/$presentationId'
    | '/bible/'
    | '/hymnal/'
    | '/presentations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibleRouteRoute: typeof BibleRouteRouteWithChildren
  HymnalRouteRoute: typeof HymnalRouteRouteWithChildren
  PresentationsRouteRoute: typeof PresentationsRouteRouteWithChildren
  ProjectorRoute: typeof ProjectorRoute
  ReturnRoute: typeof ReturnRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  UtilitiesRoute: typeof UtilitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utilities': {
      id: '/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof UtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return': {
      id: '/return'
      path: '/return'
      fullPath: '/return'
      preLoaderRoute: typeof ReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projector': {
      id: '/projector'
      path: '/projector'
      fullPath: '/projector'
      preLoaderRoute: typeof ProjectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations': {
      id: '/presentations'
      path: '/presentations'
      fullPath: '/presentations'
      preLoaderRoute: typeof PresentationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hymnal': {
      id: '/hymnal'
      path: '/hymnal'
      fullPath: '/hymnal'
      preLoaderRoute: typeof HymnalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible': {
      id: '/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof BibleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/': {
      id: '/presentations/'
      path: '/'
      fullPath: '/presentations/'
      preLoaderRoute: typeof PresentationsIndexRouteImport
      parentRoute: typeof PresentationsRouteRoute
    }
    '/hymnal/': {
      id: '/hymnal/'
      path: '/'
      fullPath: '/hymnal/'
      preLoaderRoute: typeof HymnalIndexRouteImport
      parentRoute: typeof HymnalRouteRoute
    }
    '/bible/': {
      id: '/bible/'
      path: '/'
      fullPath: '/bible/'
      preLoaderRoute: typeof BibleIndexRouteImport
      parentRoute: typeof BibleRouteRoute
    }
    '/presentations/$presentationId': {
      id: '/presentations/$presentationId'
      path: '/$presentationId'
      fullPath: '/presentations/$presentationId'
      preLoaderRoute: typeof PresentationsPresentationIdRouteImport
      parentRoute: typeof PresentationsRouteRoute
    }
    '/hymnal/$hymnId': {
      id: '/hymnal/$hymnId'
      path: '/$hymnId'
      fullPath: '/hymnal/$hymnId'
      preLoaderRoute: typeof HymnalHymnIdRouteImport
      parentRoute: typeof HymnalRouteRoute
    }
  }
}

interface BibleRouteRouteChildren {
  BibleIndexRoute: typeof BibleIndexRoute
}

const BibleRouteRouteChildren: BibleRouteRouteChildren = {
  BibleIndexRoute: BibleIndexRoute,
}

const BibleRouteRouteWithChildren = BibleRouteRoute._addFileChildren(
  BibleRouteRouteChildren,
)

interface HymnalRouteRouteChildren {
  HymnalHymnIdRoute: typeof HymnalHymnIdRoute
  HymnalIndexRoute: typeof HymnalIndexRoute
}

const HymnalRouteRouteChildren: HymnalRouteRouteChildren = {
  HymnalHymnIdRoute: HymnalHymnIdRoute,
  HymnalIndexRoute: HymnalIndexRoute,
}

const HymnalRouteRouteWithChildren = HymnalRouteRoute._addFileChildren(
  HymnalRouteRouteChildren,
)

interface PresentationsRouteRouteChildren {
  PresentationsPresentationIdRoute: typeof PresentationsPresentationIdRoute
  PresentationsIndexRoute: typeof PresentationsIndexRoute
}

const PresentationsRouteRouteChildren: PresentationsRouteRouteChildren = {
  PresentationsPresentationIdRoute: PresentationsPresentationIdRoute,
  PresentationsIndexRoute: PresentationsIndexRoute,
}

const PresentationsRouteRouteWithChildren =
  PresentationsRouteRoute._addFileChildren(PresentationsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibleRouteRoute: BibleRouteRouteWithChildren,
  HymnalRouteRoute: HymnalRouteRouteWithChildren,
  PresentationsRouteRoute: PresentationsRouteRouteWithChildren,
  ProjectorRoute: ProjectorRoute,
  ReturnRoute: ReturnRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  UtilitiesRoute: UtilitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
