/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpotlightRouteImport } from './routes/spotlight'
import { Route as ReturnRouteImport } from './routes/return'
import { Route as ProjectorRouteImport } from './routes/projector'
import { Route as IdentifyRouteImport } from './routes/identify'
import { Route as UtilitiesRouteRouteImport } from './routes/utilities/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as ServicesRouteRouteImport } from './routes/services/route'
import { Route as PresentationsRouteRouteImport } from './routes/presentations/route'
import { Route as PlayingNowRouteRouteImport } from './routes/playing-now/route'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as HymnalRouteRouteImport } from './routes/hymnal/route'
import { Route as HelpRouteRouteImport } from './routes/help/route'
import { Route as CollectionsRouteRouteImport } from './routes/collections/route'
import { Route as BibleRouteRouteImport } from './routes/bible/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UtilitiesIndexRouteImport } from './routes/utilities/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as PresentationsIndexRouteImport } from './routes/presentations/index'
import { Route as PlayingNowIndexRouteImport } from './routes/playing-now/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as HymnalIndexRouteImport } from './routes/hymnal/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as BibleIndexRouteImport } from './routes/bible/index'
import { Route as UtilitiesTimerRouteImport } from './routes/utilities/timer'
import { Route as UtilitiesTextRouteImport } from './routes/utilities/text'
import { Route as UtilitiesSchedulesRouteImport } from './routes/utilities/schedules'
import { Route as UtilitiesMediaLibraryRouteImport } from './routes/utilities/media-library'
import { Route as UtilitiesLotteryRouteImport } from './routes/utilities/lottery'
import { Route as UtilitiesInteractiveTextRouteImport } from './routes/utilities/interactive-text'
import { Route as UtilitiesClockRouteImport } from './routes/utilities/clock'
import { Route as ServicesServiceIdRouteImport } from './routes/services/$serviceId'
import { Route as PresentationsPresentationIdRouteImport } from './routes/presentations/$presentationId'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding/welcome'
import { Route as OnboardingMonitorsRouteImport } from './routes/onboarding/monitors'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding/complete'
import { Route as HymnalHymnIdRouteImport } from './routes/hymnal/$hymnId'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections/$collectionId'

const SpotlightRoute = SpotlightRouteImport.update({
  id: '/spotlight',
  path: '/spotlight',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnRoute = ReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectorRoute = ProjectorRouteImport.update({
  id: '/projector',
  path: '/projector',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentifyRoute = IdentifyRouteImport.update({
  id: '/identify',
  path: '/identify',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesRouteRoute = UtilitiesRouteRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRouteRoute = ServicesRouteRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsRouteRoute = PresentationsRouteRouteImport.update({
  id: '/presentations',
  path: '/presentations',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayingNowRouteRoute = PlayingNowRouteRouteImport.update({
  id: '/playing-now',
  path: '/playing-now',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HymnalRouteRoute = HymnalRouteRouteImport.update({
  id: '/hymnal',
  path: '/hymnal',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRouteRoute = HelpRouteRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRouteRoute = CollectionsRouteRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleRouteRoute = BibleRouteRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesIndexRoute = UtilitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UtilitiesRouteRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRouteRoute,
} as any)
const PresentationsIndexRoute = PresentationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PresentationsRouteRoute,
} as any)
const PlayingNowIndexRoute = PlayingNowIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayingNowRouteRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const HymnalIndexRoute = HymnalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HymnalRouteRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRouteRoute,
} as any)
const BibleIndexRoute = BibleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibleRouteRoute,
} as any)
const UtilitiesTimerRoute = UtilitiesTimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => UtilitiesRouteRoute,
} as any)
const UtilitiesTextRoute = UtilitiesTextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => UtilitiesRouteRoute,
} as any)
const UtilitiesSchedulesRoute = UtilitiesSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => UtilitiesRouteRoute,
} as any)
const UtilitiesMediaLibraryRoute = UtilitiesMediaLibraryRouteImport.update({
  id: '/media-library',
  path: '/media-library',
  getParentRoute: () => UtilitiesRouteRoute,
} as any)
const UtilitiesLotteryRoute = UtilitiesLotteryRouteImport.update({
  id: '/lottery',
  path: '/lottery',
  getParentRoute: () => UtilitiesRouteRoute,
} as any)
const UtilitiesInteractiveTextRoute =
  UtilitiesInteractiveTextRouteImport.update({
    id: '/interactive-text',
    path: '/interactive-text',
    getParentRoute: () => UtilitiesRouteRoute,
  } as any)
const UtilitiesClockRoute = UtilitiesClockRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => UtilitiesRouteRoute,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/$serviceId',
  path: '/$serviceId',
  getParentRoute: () => ServicesRouteRoute,
} as any)
const PresentationsPresentationIdRoute =
  PresentationsPresentationIdRouteImport.update({
    id: '/$presentationId',
    path: '/$presentationId',
    getParentRoute: () => PresentationsRouteRoute,
  } as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingMonitorsRoute = OnboardingMonitorsRouteImport.update({
  id: '/monitors',
  path: '/monitors',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const HymnalHymnIdRoute = HymnalHymnIdRouteImport.update({
  id: '/$hymnId',
  path: '/$hymnId',
  getParentRoute: () => HymnalRouteRoute,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/$collectionId',
  path: '/$collectionId',
  getParentRoute: () => CollectionsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bible': typeof BibleRouteRouteWithChildren
  '/collections': typeof CollectionsRouteRouteWithChildren
  '/help': typeof HelpRouteRoute
  '/hymnal': typeof HymnalRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/playing-now': typeof PlayingNowRouteRouteWithChildren
  '/presentations': typeof PresentationsRouteRouteWithChildren
  '/services': typeof ServicesRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/utilities': typeof UtilitiesRouteRouteWithChildren
  '/identify': typeof IdentifyRoute
  '/projector': typeof ProjectorRoute
  '/return': typeof ReturnRoute
  '/spotlight': typeof SpotlightRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/hymnal/$hymnId': typeof HymnalHymnIdRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/monitors': typeof OnboardingMonitorsRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/presentations/$presentationId': typeof PresentationsPresentationIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/utilities/clock': typeof UtilitiesClockRoute
  '/utilities/interactive-text': typeof UtilitiesInteractiveTextRoute
  '/utilities/lottery': typeof UtilitiesLotteryRoute
  '/utilities/media-library': typeof UtilitiesMediaLibraryRoute
  '/utilities/schedules': typeof UtilitiesSchedulesRoute
  '/utilities/text': typeof UtilitiesTextRoute
  '/utilities/timer': typeof UtilitiesTimerRoute
  '/bible/': typeof BibleIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/hymnal/': typeof HymnalIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/playing-now/': typeof PlayingNowIndexRoute
  '/presentations/': typeof PresentationsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/utilities/': typeof UtilitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRouteRoute
  '/identify': typeof IdentifyRoute
  '/projector': typeof ProjectorRoute
  '/return': typeof ReturnRoute
  '/spotlight': typeof SpotlightRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/hymnal/$hymnId': typeof HymnalHymnIdRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/monitors': typeof OnboardingMonitorsRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/presentations/$presentationId': typeof PresentationsPresentationIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/utilities/clock': typeof UtilitiesClockRoute
  '/utilities/interactive-text': typeof UtilitiesInteractiveTextRoute
  '/utilities/lottery': typeof UtilitiesLotteryRoute
  '/utilities/media-library': typeof UtilitiesMediaLibraryRoute
  '/utilities/schedules': typeof UtilitiesSchedulesRoute
  '/utilities/text': typeof UtilitiesTextRoute
  '/utilities/timer': typeof UtilitiesTimerRoute
  '/bible': typeof BibleIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/hymnal': typeof HymnalIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/playing-now': typeof PlayingNowIndexRoute
  '/presentations': typeof PresentationsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/utilities': typeof UtilitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bible': typeof BibleRouteRouteWithChildren
  '/collections': typeof CollectionsRouteRouteWithChildren
  '/help': typeof HelpRouteRoute
  '/hymnal': typeof HymnalRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/playing-now': typeof PlayingNowRouteRouteWithChildren
  '/presentations': typeof PresentationsRouteRouteWithChildren
  '/services': typeof ServicesRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/utilities': typeof UtilitiesRouteRouteWithChildren
  '/identify': typeof IdentifyRoute
  '/projector': typeof ProjectorRoute
  '/return': typeof ReturnRoute
  '/spotlight': typeof SpotlightRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/hymnal/$hymnId': typeof HymnalHymnIdRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/monitors': typeof OnboardingMonitorsRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/presentations/$presentationId': typeof PresentationsPresentationIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/utilities/clock': typeof UtilitiesClockRoute
  '/utilities/interactive-text': typeof UtilitiesInteractiveTextRoute
  '/utilities/lottery': typeof UtilitiesLotteryRoute
  '/utilities/media-library': typeof UtilitiesMediaLibraryRoute
  '/utilities/schedules': typeof UtilitiesSchedulesRoute
  '/utilities/text': typeof UtilitiesTextRoute
  '/utilities/timer': typeof UtilitiesTimerRoute
  '/bible/': typeof BibleIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/hymnal/': typeof HymnalIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/playing-now/': typeof PlayingNowIndexRoute
  '/presentations/': typeof PresentationsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/utilities/': typeof UtilitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bible'
    | '/collections'
    | '/help'
    | '/hymnal'
    | '/onboarding'
    | '/playing-now'
    | '/presentations'
    | '/services'
    | '/settings'
    | '/utilities'
    | '/identify'
    | '/projector'
    | '/return'
    | '/spotlight'
    | '/collections/$collectionId'
    | '/hymnal/$hymnId'
    | '/onboarding/complete'
    | '/onboarding/monitors'
    | '/onboarding/welcome'
    | '/presentations/$presentationId'
    | '/services/$serviceId'
    | '/utilities/clock'
    | '/utilities/interactive-text'
    | '/utilities/lottery'
    | '/utilities/media-library'
    | '/utilities/schedules'
    | '/utilities/text'
    | '/utilities/timer'
    | '/bible/'
    | '/collections/'
    | '/hymnal/'
    | '/onboarding/'
    | '/playing-now/'
    | '/presentations/'
    | '/services/'
    | '/settings/'
    | '/utilities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/identify'
    | '/projector'
    | '/return'
    | '/spotlight'
    | '/collections/$collectionId'
    | '/hymnal/$hymnId'
    | '/onboarding/complete'
    | '/onboarding/monitors'
    | '/onboarding/welcome'
    | '/presentations/$presentationId'
    | '/services/$serviceId'
    | '/utilities/clock'
    | '/utilities/interactive-text'
    | '/utilities/lottery'
    | '/utilities/media-library'
    | '/utilities/schedules'
    | '/utilities/text'
    | '/utilities/timer'
    | '/bible'
    | '/collections'
    | '/hymnal'
    | '/onboarding'
    | '/playing-now'
    | '/presentations'
    | '/services'
    | '/settings'
    | '/utilities'
  id:
    | '__root__'
    | '/'
    | '/bible'
    | '/collections'
    | '/help'
    | '/hymnal'
    | '/onboarding'
    | '/playing-now'
    | '/presentations'
    | '/services'
    | '/settings'
    | '/utilities'
    | '/identify'
    | '/projector'
    | '/return'
    | '/spotlight'
    | '/collections/$collectionId'
    | '/hymnal/$hymnId'
    | '/onboarding/complete'
    | '/onboarding/monitors'
    | '/onboarding/welcome'
    | '/presentations/$presentationId'
    | '/services/$serviceId'
    | '/utilities/clock'
    | '/utilities/interactive-text'
    | '/utilities/lottery'
    | '/utilities/media-library'
    | '/utilities/schedules'
    | '/utilities/text'
    | '/utilities/timer'
    | '/bible/'
    | '/collections/'
    | '/hymnal/'
    | '/onboarding/'
    | '/playing-now/'
    | '/presentations/'
    | '/services/'
    | '/settings/'
    | '/utilities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibleRouteRoute: typeof BibleRouteRouteWithChildren
  CollectionsRouteRoute: typeof CollectionsRouteRouteWithChildren
  HelpRouteRoute: typeof HelpRouteRoute
  HymnalRouteRoute: typeof HymnalRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  PlayingNowRouteRoute: typeof PlayingNowRouteRouteWithChildren
  PresentationsRouteRoute: typeof PresentationsRouteRouteWithChildren
  ServicesRouteRoute: typeof ServicesRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  UtilitiesRouteRoute: typeof UtilitiesRouteRouteWithChildren
  IdentifyRoute: typeof IdentifyRoute
  ProjectorRoute: typeof ProjectorRoute
  ReturnRoute: typeof ReturnRoute
  SpotlightRoute: typeof SpotlightRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spotlight': {
      id: '/spotlight'
      path: '/spotlight'
      fullPath: '/spotlight'
      preLoaderRoute: typeof SpotlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return': {
      id: '/return'
      path: '/return'
      fullPath: '/return'
      preLoaderRoute: typeof ReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projector': {
      id: '/projector'
      path: '/projector'
      fullPath: '/projector'
      preLoaderRoute: typeof ProjectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identify': {
      id: '/identify'
      path: '/identify'
      fullPath: '/identify'
      preLoaderRoute: typeof IdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities': {
      id: '/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof UtilitiesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations': {
      id: '/presentations'
      path: '/presentations'
      fullPath: '/presentations'
      preLoaderRoute: typeof PresentationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playing-now': {
      id: '/playing-now'
      path: '/playing-now'
      fullPath: '/playing-now'
      preLoaderRoute: typeof PlayingNowRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hymnal': {
      id: '/hymnal'
      path: '/hymnal'
      fullPath: '/hymnal'
      preLoaderRoute: typeof HymnalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible': {
      id: '/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof BibleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/': {
      id: '/utilities/'
      path: '/'
      fullPath: '/utilities/'
      preLoaderRoute: typeof UtilitiesIndexRouteImport
      parentRoute: typeof UtilitiesRouteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/presentations/': {
      id: '/presentations/'
      path: '/'
      fullPath: '/presentations/'
      preLoaderRoute: typeof PresentationsIndexRouteImport
      parentRoute: typeof PresentationsRouteRoute
    }
    '/playing-now/': {
      id: '/playing-now/'
      path: '/'
      fullPath: '/playing-now/'
      preLoaderRoute: typeof PlayingNowIndexRouteImport
      parentRoute: typeof PlayingNowRouteRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/hymnal/': {
      id: '/hymnal/'
      path: '/'
      fullPath: '/hymnal/'
      preLoaderRoute: typeof HymnalIndexRouteImport
      parentRoute: typeof HymnalRouteRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRouteRoute
    }
    '/bible/': {
      id: '/bible/'
      path: '/'
      fullPath: '/bible/'
      preLoaderRoute: typeof BibleIndexRouteImport
      parentRoute: typeof BibleRouteRoute
    }
    '/utilities/timer': {
      id: '/utilities/timer'
      path: '/timer'
      fullPath: '/utilities/timer'
      preLoaderRoute: typeof UtilitiesTimerRouteImport
      parentRoute: typeof UtilitiesRouteRoute
    }
    '/utilities/text': {
      id: '/utilities/text'
      path: '/text'
      fullPath: '/utilities/text'
      preLoaderRoute: typeof UtilitiesTextRouteImport
      parentRoute: typeof UtilitiesRouteRoute
    }
    '/utilities/schedules': {
      id: '/utilities/schedules'
      path: '/schedules'
      fullPath: '/utilities/schedules'
      preLoaderRoute: typeof UtilitiesSchedulesRouteImport
      parentRoute: typeof UtilitiesRouteRoute
    }
    '/utilities/media-library': {
      id: '/utilities/media-library'
      path: '/media-library'
      fullPath: '/utilities/media-library'
      preLoaderRoute: typeof UtilitiesMediaLibraryRouteImport
      parentRoute: typeof UtilitiesRouteRoute
    }
    '/utilities/lottery': {
      id: '/utilities/lottery'
      path: '/lottery'
      fullPath: '/utilities/lottery'
      preLoaderRoute: typeof UtilitiesLotteryRouteImport
      parentRoute: typeof UtilitiesRouteRoute
    }
    '/utilities/interactive-text': {
      id: '/utilities/interactive-text'
      path: '/interactive-text'
      fullPath: '/utilities/interactive-text'
      preLoaderRoute: typeof UtilitiesInteractiveTextRouteImport
      parentRoute: typeof UtilitiesRouteRoute
    }
    '/utilities/clock': {
      id: '/utilities/clock'
      path: '/clock'
      fullPath: '/utilities/clock'
      preLoaderRoute: typeof UtilitiesClockRouteImport
      parentRoute: typeof UtilitiesRouteRoute
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/presentations/$presentationId': {
      id: '/presentations/$presentationId'
      path: '/$presentationId'
      fullPath: '/presentations/$presentationId'
      preLoaderRoute: typeof PresentationsPresentationIdRouteImport
      parentRoute: typeof PresentationsRouteRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/monitors': {
      id: '/onboarding/monitors'
      path: '/monitors'
      fullPath: '/onboarding/monitors'
      preLoaderRoute: typeof OnboardingMonitorsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/hymnal/$hymnId': {
      id: '/hymnal/$hymnId'
      path: '/$hymnId'
      fullPath: '/hymnal/$hymnId'
      preLoaderRoute: typeof HymnalHymnIdRouteImport
      parentRoute: typeof HymnalRouteRoute
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof CollectionsRouteRoute
    }
  }
}

interface BibleRouteRouteChildren {
  BibleIndexRoute: typeof BibleIndexRoute
}

const BibleRouteRouteChildren: BibleRouteRouteChildren = {
  BibleIndexRoute: BibleIndexRoute,
}

const BibleRouteRouteWithChildren = BibleRouteRoute._addFileChildren(
  BibleRouteRouteChildren,
)

interface CollectionsRouteRouteChildren {
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

const CollectionsRouteRouteChildren: CollectionsRouteRouteChildren = {
  CollectionsCollectionIdRoute: CollectionsCollectionIdRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}

const CollectionsRouteRouteWithChildren =
  CollectionsRouteRoute._addFileChildren(CollectionsRouteRouteChildren)

interface HymnalRouteRouteChildren {
  HymnalHymnIdRoute: typeof HymnalHymnIdRoute
  HymnalIndexRoute: typeof HymnalIndexRoute
}

const HymnalRouteRouteChildren: HymnalRouteRouteChildren = {
  HymnalHymnIdRoute: HymnalHymnIdRoute,
  HymnalIndexRoute: HymnalIndexRoute,
}

const HymnalRouteRouteWithChildren = HymnalRouteRoute._addFileChildren(
  HymnalRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingMonitorsRoute: typeof OnboardingMonitorsRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingMonitorsRoute: OnboardingMonitorsRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface PlayingNowRouteRouteChildren {
  PlayingNowIndexRoute: typeof PlayingNowIndexRoute
}

const PlayingNowRouteRouteChildren: PlayingNowRouteRouteChildren = {
  PlayingNowIndexRoute: PlayingNowIndexRoute,
}

const PlayingNowRouteRouteWithChildren = PlayingNowRouteRoute._addFileChildren(
  PlayingNowRouteRouteChildren,
)

interface PresentationsRouteRouteChildren {
  PresentationsPresentationIdRoute: typeof PresentationsPresentationIdRoute
  PresentationsIndexRoute: typeof PresentationsIndexRoute
}

const PresentationsRouteRouteChildren: PresentationsRouteRouteChildren = {
  PresentationsPresentationIdRoute: PresentationsPresentationIdRoute,
  PresentationsIndexRoute: PresentationsIndexRoute,
}

const PresentationsRouteRouteWithChildren =
  PresentationsRouteRoute._addFileChildren(PresentationsRouteRouteChildren)

interface ServicesRouteRouteChildren {
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteRouteChildren: ServicesRouteRouteChildren = {
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteRouteWithChildren = ServicesRouteRoute._addFileChildren(
  ServicesRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface UtilitiesRouteRouteChildren {
  UtilitiesClockRoute: typeof UtilitiesClockRoute
  UtilitiesInteractiveTextRoute: typeof UtilitiesInteractiveTextRoute
  UtilitiesLotteryRoute: typeof UtilitiesLotteryRoute
  UtilitiesMediaLibraryRoute: typeof UtilitiesMediaLibraryRoute
  UtilitiesSchedulesRoute: typeof UtilitiesSchedulesRoute
  UtilitiesTextRoute: typeof UtilitiesTextRoute
  UtilitiesTimerRoute: typeof UtilitiesTimerRoute
  UtilitiesIndexRoute: typeof UtilitiesIndexRoute
}

const UtilitiesRouteRouteChildren: UtilitiesRouteRouteChildren = {
  UtilitiesClockRoute: UtilitiesClockRoute,
  UtilitiesInteractiveTextRoute: UtilitiesInteractiveTextRoute,
  UtilitiesLotteryRoute: UtilitiesLotteryRoute,
  UtilitiesMediaLibraryRoute: UtilitiesMediaLibraryRoute,
  UtilitiesSchedulesRoute: UtilitiesSchedulesRoute,
  UtilitiesTextRoute: UtilitiesTextRoute,
  UtilitiesTimerRoute: UtilitiesTimerRoute,
  UtilitiesIndexRoute: UtilitiesIndexRoute,
}

const UtilitiesRouteRouteWithChildren = UtilitiesRouteRoute._addFileChildren(
  UtilitiesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibleRouteRoute: BibleRouteRouteWithChildren,
  CollectionsRouteRoute: CollectionsRouteRouteWithChildren,
  HelpRouteRoute: HelpRouteRoute,
  HymnalRouteRoute: HymnalRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  PlayingNowRouteRoute: PlayingNowRouteRouteWithChildren,
  PresentationsRouteRoute: PresentationsRouteRouteWithChildren,
  ServicesRouteRoute: ServicesRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  UtilitiesRouteRoute: UtilitiesRouteRouteWithChildren,
  IdentifyRoute: IdentifyRoute,
  ProjectorRoute: ProjectorRoute,
  ReturnRoute: ReturnRoute,
  SpotlightRoute: SpotlightRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
