/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilitiesRouteImport } from './routes/utilities'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReturnRouteImport } from './routes/return'
import { Route as ProjectorRouteImport } from './routes/projector'
import { Route as PresentationsRouteImport } from './routes/presentations'
import { Route as BibleRouteImport } from './routes/bible'
import { Route as HymnalRouteRouteImport } from './routes/hymnal/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HymnalIndexRouteImport } from './routes/hymnal/index'
import { Route as HymnalHymnIdRouteImport } from './routes/hymnal/$hymnId'

const UtilitiesRoute = UtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnRoute = ReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectorRoute = ProjectorRouteImport.update({
  id: '/projector',
  path: '/projector',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsRoute = PresentationsRouteImport.update({
  id: '/presentations',
  path: '/presentations',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleRoute = BibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => rootRouteImport,
} as any)
const HymnalRouteRoute = HymnalRouteRouteImport.update({
  id: '/hymnal',
  path: '/hymnal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HymnalIndexRoute = HymnalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HymnalRouteRoute,
} as any)
const HymnalHymnIdRoute = HymnalHymnIdRouteImport.update({
  id: '/$hymnId',
  path: '/$hymnId',
  getParentRoute: () => HymnalRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hymnal': typeof HymnalRouteRouteWithChildren
  '/bible': typeof BibleRoute
  '/presentations': typeof PresentationsRoute
  '/projector': typeof ProjectorRoute
  '/return': typeof ReturnRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/utilities': typeof UtilitiesRoute
  '/hymnal/$hymnId': typeof HymnalHymnIdRoute
  '/hymnal/': typeof HymnalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bible': typeof BibleRoute
  '/presentations': typeof PresentationsRoute
  '/projector': typeof ProjectorRoute
  '/return': typeof ReturnRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/utilities': typeof UtilitiesRoute
  '/hymnal/$hymnId': typeof HymnalHymnIdRoute
  '/hymnal': typeof HymnalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hymnal': typeof HymnalRouteRouteWithChildren
  '/bible': typeof BibleRoute
  '/presentations': typeof PresentationsRoute
  '/projector': typeof ProjectorRoute
  '/return': typeof ReturnRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/utilities': typeof UtilitiesRoute
  '/hymnal/$hymnId': typeof HymnalHymnIdRoute
  '/hymnal/': typeof HymnalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hymnal'
    | '/bible'
    | '/presentations'
    | '/projector'
    | '/return'
    | '/services'
    | '/settings'
    | '/utilities'
    | '/hymnal/$hymnId'
    | '/hymnal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bible'
    | '/presentations'
    | '/projector'
    | '/return'
    | '/services'
    | '/settings'
    | '/utilities'
    | '/hymnal/$hymnId'
    | '/hymnal'
  id:
    | '__root__'
    | '/'
    | '/hymnal'
    | '/bible'
    | '/presentations'
    | '/projector'
    | '/return'
    | '/services'
    | '/settings'
    | '/utilities'
    | '/hymnal/$hymnId'
    | '/hymnal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HymnalRouteRoute: typeof HymnalRouteRouteWithChildren
  BibleRoute: typeof BibleRoute
  PresentationsRoute: typeof PresentationsRoute
  ProjectorRoute: typeof ProjectorRoute
  ReturnRoute: typeof ReturnRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  UtilitiesRoute: typeof UtilitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utilities': {
      id: '/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof UtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return': {
      id: '/return'
      path: '/return'
      fullPath: '/return'
      preLoaderRoute: typeof ReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projector': {
      id: '/projector'
      path: '/projector'
      fullPath: '/projector'
      preLoaderRoute: typeof ProjectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations': {
      id: '/presentations'
      path: '/presentations'
      fullPath: '/presentations'
      preLoaderRoute: typeof PresentationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible': {
      id: '/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof BibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hymnal': {
      id: '/hymnal'
      path: '/hymnal'
      fullPath: '/hymnal'
      preLoaderRoute: typeof HymnalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hymnal/': {
      id: '/hymnal/'
      path: '/'
      fullPath: '/hymnal/'
      preLoaderRoute: typeof HymnalIndexRouteImport
      parentRoute: typeof HymnalRouteRoute
    }
    '/hymnal/$hymnId': {
      id: '/hymnal/$hymnId'
      path: '/$hymnId'
      fullPath: '/hymnal/$hymnId'
      preLoaderRoute: typeof HymnalHymnIdRouteImport
      parentRoute: typeof HymnalRouteRoute
    }
  }
}

interface HymnalRouteRouteChildren {
  HymnalHymnIdRoute: typeof HymnalHymnIdRoute
  HymnalIndexRoute: typeof HymnalIndexRoute
}

const HymnalRouteRouteChildren: HymnalRouteRouteChildren = {
  HymnalHymnIdRoute: HymnalHymnIdRoute,
  HymnalIndexRoute: HymnalIndexRoute,
}

const HymnalRouteRouteWithChildren = HymnalRouteRoute._addFileChildren(
  HymnalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HymnalRouteRoute: HymnalRouteRouteWithChildren,
  BibleRoute: BibleRoute,
  PresentationsRoute: PresentationsRoute,
  ProjectorRoute: ProjectorRoute,
  ReturnRoute: ReturnRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  UtilitiesRoute: UtilitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
