import { invoke } from "@tauri-apps/api/core";
import { commands, type AppErrorResponse, type MediaSource, type Result } from "../bindings";

function unwrap<T>(result: Result<T, AppErrorResponse>): T {
  if (result.status === "error") {
    // P3.19 — surface the *actual* Rust-side detail, not the generic
    // "An internal application error occurred." message that AppError's
    // serde impl always produces for the `Internal` variant. The detail
    // string carries the file:line + format!() context (e.g.
    // "video_pipeline.seek(12.300s) from Playing: gstreamer SeekFailed").
    // Without this, every loop / seek / restart failure surfaced a single
    // identical toast that gave the user (and dogfood reviewers) zero
    // diagnostic signal — and made it impossible to tell whether
    // earlier-round fixes (P3.13's improved format strings) had landed at
    // all. Composite "msg — details" so the toast is still self-contained
    // when displayed without a description body.
    const generic = "An internal application error occurred.";
    const baseMessage = result.error?.message ?? "video pipeline error";
    const details = result.error?.details ?? null;
    const composed =
      baseMessage === generic && details
        ? details
        : details && details !== baseMessage
          ? `${baseMessage} — ${details}`
          : baseMessage;
    throw new Error(composed);
  }
  return result.data;
}

/**
 * Subscribe a window to the Rust video pipeline. Triggers an SDP offer
 * to flow back via the `videoPipelineOffer` typed event.
 */
export async function subscribe(windowLabel: string): Promise<null> {
  return unwrap(await commands.videoPipelineSubscribe(windowLabel));
}

/**
 * Tear down the Rust-side WebRTC consumer for the given window.
 */
export async function unsubscribe(windowLabel: string): Promise<null> {
  return unwrap(await commands.videoPipelineUnsubscribe(windowLabel));
}

/**
 * Forward an SDP answer from the frontend `RTCPeerConnection` back to Rust.
 */
export async function sendAnswer(windowLabel: string, sdp: string): Promise<null> {
  return unwrap(await commands.videoPipelineAnswer(windowLabel, sdp));
}

/**
 * Forward a local ICE candidate from the frontend `RTCPeerConnection` to Rust.
 * For the end-of-candidates sentinel, callers should pass an empty string.
 */
export async function sendIce(
  windowLabel: string,
  candidate: string,
  sdpMLineIndex: number,
): Promise<null> {
  return unwrap(await commands.videoPipelineIce(windowLabel, candidate, sdpMLineIndex));
}

/**
 * Resolve `source` to a GStreamer URI and load it on the pipeline.
 */
export async function load(source: MediaSource): Promise<null> {
  return unwrap(await commands.videoPipelineLoad(source));
}

/** Transition the pipeline to PLAYING. */
export async function play(): Promise<null> {
  return unwrap(await commands.videoPipelinePlay());
}

/** Transition the pipeline to PAUSED. */
export async function pause(): Promise<null> {
  return unwrap(await commands.videoPipelinePause());
}

/** Seek the pipeline to `secs`. */
export async function seek(secs: number): Promise<null> {
  return unwrap(await commands.videoPipelineSeek(secs));
}

/**
 * Update the playback volume (0.0–1.0). Sets the `volume` property on the
 * live `audio_volume` element and mirrors to the state snapshot.
 */
export async function setVolume(volume: number): Promise<null> {
  return unwrap(await commands.videoPipelineSetVolume(volume));
}

/** Tear down the pipeline and reset the snapshot. */
export async function unload(): Promise<null> {
  return unwrap(await commands.videoPipelineUnload());
}

/** Seek to 0 and resume PLAYING (Task 3.1). */
export async function restart(): Promise<null> {
  return unwrap(await commands.videoPipelineRestart());
}

/** Set the loop mode (Task 3.1). */
export async function setLoop(mode: "none" | "one"): Promise<null> {
  return unwrap(await commands.videoPipelineSetLoop(mode));
}

/**
 * Attach the native GStreamer sink for `windowLabel` so the shared pipeline
 * renders directly into that window's OS surface (Phase 3 of the
 * frame-perfect multi-monitor video plan).
 *
 * Uses an untyped `invoke` because the typed bindings in `bindings.ts` are
 * regenerated by `pnpm tauri dev`; we keep this call working before/after
 * regen so the implementation isn't bound to a single bindings refresh.
 */
export async function attachWindow(windowLabel: string): Promise<void> {
  await invoke("video_pipeline_attach_window", { label: windowLabel });
}

/** Detach the native sink for `windowLabel`. Companion to [`attachWindow`]. */
export async function detachWindow(windowLabel: string): Promise<void> {
  await invoke("video_pipeline_detach_window", { label: windowLabel });
}
